### ISSUE TITLE
InotifyTrees raises exception in log call for bytes argument (expecting str)

### ISSUE THREAD

**Issue by hathcock** [dsoprea/PyInotify#25]
Reproduce:

```py
from inotify.adapters import InotifyTrees

inots = InotifyTrees([
    b"something/",
    b"else/"
])
```

Results in:
```sh
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    b"output_files"
  File "/home/myles/software/conda/envs/dev35/lib/python3.5/site-packages/inotify/adapters.py", line 261, in __init__
    self.__load_trees(paths)
  File "/home/myles/software/conda/envs/dev35/lib/python3.5/site-packages/inotify/adapters.py", line 264, in __load_trees
    _LOGGER.debug("Adding initial watches on trees: [%s]", ",".join(paths))
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by davidparsson** [comment]
I'm having this issue as well.

@dsoprea, what are the chances that there will be a release including this anytime soon?
