### ISSUE TITLE
inotify can not run properly under alpine linux

### ISSUE THREAD

**Issue by ilovemath** [dsoprea/PyInotify#44]
When I user inotify under alpine linux, it shows such error:
Traceback (most recent call last):
File "", line 1, in 
File "/usr/lib/python3.6/site-packages/inotify/adapters.py", line 10, in 
import inotify.calls
File "/usr/lib/python3.6/site-packages/inotify/calls.py", line 55, in 
errno = _LIB.errno
File "/usr/lib/python3.6/ctypes/init.py", line 361, in getattr
func = self.getitem(name)
File "/usr/lib/python3.6/ctypes/init.py", line 366, in getitem
func = self._FuncPtr((name_or_ordinal, self))
AttributeError: Symbol not found: errno

**Comment by blag** [comment]
What version of Alpine?

**Comment by ilovemath** [comment]
@blag  docker image，alpine:3.7

**Comment by jonathanverner** [comment]
I think this was fixed in https://github.com/dsoprea/PyInotify/pull/27
