### ISSUE TITLE
Inotify.__handle_inotify_event raises TypeError when attempting to handle an event in python3.

### ISSUE THREAD

**Issue by declaresub** [dsoprea/PyInotify#6]
Stack trace:

Traceback (most recent call last):
  File "/inotify/dev/test.py", line 50, in <module>
    _main()
  File "/inotify/dev/test.py", line 38, in _main
    for event in i.event_gen():
  File "/inotify/inotify/adapters.py", line 162, in event_gen
    in self.__handle_inotify_event(fd, event_type):
  File "/inotify/inotify/adapters.py", line 114, in __handle_inotify_event
    self.__buffer += b
TypeError: Can't convert 'bytes' object to str implicitly

The problem is that self.__buffer is initialized to '', which in python 3 is a unicode string.

**Comment by sergio91pt** [comment]
Fixed in 74d182112332269d436b8381c02468f95fa87ca3
